### ISSUE TITLE
Error with facility meltdown

### ISSUE THREAD

**Issue by Friskzips** [Saradora/UnityMDK#2]
When facility meltdown and Unity mdk (idk if its only with unity mdk because im using scantweaks mod that requires this lib)
are in the same modpack, I get this error.
![error](https://github.com/Saradora/UnityMDK/assets/99197717/aafe2bd4-caa3-40e0-adfc-f3630c9304bb)
I don't think that it does anything, but errors aren't cool.

**Comment by Saradora** [comment]
Hello!
Thanks for the feedback!
I added the error message because some mods were interfering with UnityMDK (like FacilityMeltdown or LethalExpansionCore)

The message will stay because it really is an issue from those mods, and I need to be aware of it when making my own c:

But you're right that errors aren't cool, so I will try to make it more clear that this message isn't actually harmful in most cases!

**Comment by Saradora** [comment]
The error message has been tweaked to this:
![image](https://github.com/Saradora/UnityMDK/assets/22128561/b51cd297-eab6-414e-b0ac-850ce2823719)

I hope it's enough c: I will close this issue for now

**Comment by Friskzips** [comment]
Yes, better. Thanks for making an awesome mod
